remotetheme: just-the-docs/just-the-docs
title: Regression to the Mean
description: Daniel García Hernández's personal site
url: "https://dgarhdez.github.io"
repository: dgarhdez/dgarhdez.github.io # for github-metadata plugin
permalink: pretty

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

plugins:
  - jemoji
